### ISSUE TITLE
How to get rid of the "Fork Me" corner?

### ISSUE THREAD

**Issue by batjko** [juliancwirko/abc#2]
Hi,

I like the theme, but when I switch to it actually has the fork me on Github label in the corner.
How do I get rid of it?

Thanks.

**Comment by juliancwirko** [comment]
Hi, you will find it here: https://github.com/juliancwirko/abc/blob/master/index.hbs#L27 (index.hbs file)

**Comment by batjko** [comment]
Great, thanks for that quick response!
And good work!
